/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "4bb19460e8d88c3446b360b0df8fd991fee49c0b"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
