/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "1b2360b683307834aa1abe2da0e596d9832e7d53"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
